// Mock data for development — will be replaced with real Supabase queries

export const mockFilms = [
  {
    id: '1',
    title: 'Shadows of the Forgotten',
    tagline: 'Some memories refuse to stay buried.',
    genre: ['Drama', 'Thriller'],
    duration_minutes: 94,
    release_year: 2025,
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200&h=600&fit=crop',
    status: 'live' as const,
    featured: true,
    view_count: 12400,
    creator_name: 'Ava Chen',
    creator_slug: 'ava-chen',
  },
  {
    id: '2',
    title: 'Neon Requiem',
    tagline: 'The city never sleeps. Neither do its ghosts.',
    genre: ['Sci-Fi', 'Noir'],
    duration_minutes: 108,
    release_year: 2025,
    poster_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=600&fit=crop',
    status: 'live' as const,
    featured: true,
    view_count: 8200,
    creator_name: 'Marcus Webb',
    creator_slug: 'marcus-webb',
  },
  {
    id: '3',
    title: 'The Last Frame',
    tagline: 'Every picture tells a story. This one tells a lie.',
    genre: ['Mystery', 'Drama'],
    duration_minutes: 87,
    release_year: 2024,
    poster_url: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=1200&h=600&fit=crop',
    status: 'live' as const,
    featured: false,
    view_count: 5600,
    creator_name: 'Lena Park',
    creator_slug: 'lena-park',
  },
  {
    id: '4',
    title: 'Dust & Devotion',
    tagline: 'Faith tested by fire.',
    genre: ['Documentary'],
    duration_minutes: 72,
    release_year: 2025,
    poster_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=600&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&h=600&fit=crop',
    status: 'live' as const,
    featured: false,
    view_count: 3100,
    creator_name: 'Jordan Ellis',
    creator_slug: 'jordan-ellis',
  },
  {
    id: '5',
    title: 'Parallax',
    tagline: 'Two timelines. One truth.',
    genre: ['Sci-Fi', 'Thriller'],
    duration_minutes: 101,
    release_year: 2024,
    poster_url: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=400&h=600&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=1200&h=600&fit=crop',
    status: 'live' as const,
    featured: true,
    view_count: 9700,
    creator_name: 'Ava Chen',
    creator_slug: 'ava-chen',
  },
  {
    id: '6',
    title: 'Velvet Noir',
    tagline: 'Style is a weapon.',
    genre: ['Drama', 'Romance'],
    duration_minutes: 91,
    release_year: 2025,
    poster_url: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=400&h=600&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=1200&h=600&fit=crop',
    status: 'live' as const,
    featured: false,
    view_count: 4500,
    creator_name: 'Marcus Webb',
    creator_slug: 'marcus-webb',
  },
];

export const mockShorts = [
  {
    id: '1',
    title: 'The Waiting Room',
    description: 'A surreal meditation on time.',
    thumbnail_url: 'https://images.unsplash.com/photo-1518676590747-1e3dcf5a3aaf?w=360&h=640&fit=crop',
    duration_seconds: 180,
    genre: ['Drama'],
    status: 'live' as const,
    view_count: 24000,
    creator_name: 'Lena Park',
  },
  {
    id: '2',
    title: 'Frequency',
    description: 'Sound becomes sight.',
    thumbnail_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=360&h=640&fit=crop',
    duration_seconds: 120,
    genre: ['Experimental'],
    status: 'live' as const,
    view_count: 18500,
    creator_name: 'Jordan Ellis',
  },
  {
    id: '3',
    title: 'Concrete Dreams',
    description: 'Urban poetry in motion.',
    thumbnail_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=360&h=640&fit=crop',
    duration_seconds: 90,
    genre: ['Documentary'],
    status: 'live' as const,
    view_count: 15200,
    creator_name: 'Ava Chen',
  },
  {
    id: '4',
    title: 'Ghost Protocol',
    description: 'They erased her. She remembered.',
    thumbnail_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=360&h=640&fit=crop',
    duration_seconds: 240,
    genre: ['Thriller'],
    status: 'live' as const,
    view_count: 31000,
    creator_name: 'Marcus Webb',
  },
];

export const mockCreators = [
  {
    id: '1',
    display_name: 'Ava Chen',
    slug: 'ava-chen',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    bio: 'Sci-fi storyteller blending technology with human emotion.',
    genre_focus: ['Sci-Fi', 'Drama'],
    film_count: 3,
  },
  {
    id: '2',
    display_name: 'Marcus Webb',
    slug: 'marcus-webb',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    bio: 'Noir enthusiast. Every shadow has a story.',
    genre_focus: ['Noir', 'Thriller'],
    film_count: 2,
  },
  {
    id: '3',
    display_name: 'Lena Park',
    slug: 'lena-park',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    bio: 'Visual poet exploring memory and identity.',
    genre_focus: ['Drama', 'Experimental'],
    film_count: 2,
  },
  {
    id: '4',
    display_name: 'Jordan Ellis',
    slug: 'jordan-ellis',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    bio: 'Documentary filmmaker chasing truth in unexpected places.',
    genre_focus: ['Documentary'],
    film_count: 1,
  },
];

export const genres = [
  'Drama', 'Thriller', 'Sci-Fi', 'Documentary', 'Horror', 'Comedy',
  'Romance', 'Mystery', 'Experimental', 'Noir', 'Animation', 'Action',
];

export const faqItems = [
  {
    question: 'What is OPPRIME.tv?',
    answer: 'OPPRIME.tv is a premium streaming platform exclusively for independent filmmakers. We showcase features, shorts, and vertical content from creators worldwide.',
  },
  {
    question: 'How do I submit my film?',
    answer: 'Create a free creator account, then use our 5-step submission wizard to upload your film, add metadata, agree to our distribution terms, and submit for review.',
  },
  {
    question: 'What types of content can I upload?',
    answer: 'We accept feature films, short films, documentaries, series episodes, and vertical shorts. All genres welcome.',
  },
  {
    question: 'Is there a fee to submit?',
    answer: 'Submitting your work is completely free. OPPRIME operates on a revenue-share model — you earn when your content is watched.',
  },
  {
    question: 'How long does the review process take?',
    answer: 'Our curatorial team reviews submissions within 5-10 business days. You\'ll receive status updates in your creator dashboard.',
  },
  {
    question: 'What are the technical requirements?',
    answer: 'We accept MP4/MOV files up to 10GB. Minimum resolution: 1080p for features, 720x1280 for vertical shorts. Audio: stereo or 5.1 surround.',
  },
];
